export enum EInvoiceStatus {
  PENDING = 'PENDING',
  PAID = 'PAID',
  CANCELED = 'CANCELED',
  IN_ANALYSIS = 'IN_ANALYSIS',
  DRAFT = 'DRAFT',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  REFUNDED = 'REFUNDED',
  EXPIRED = 'EXPIRED',
  IN_PROTEST = 'IN_PROTEST',
  CHARGEBACK = 'CHARGEBACK',
  EXTERNALLY_PAID = 'EXTERNALLY_PAID',
}
