export enum EFcmSkill {
  PREVIEW_NATI_V1_ITEMS = 'PREVIEW_NATI_V1_ITEMS',
  REQUEST_NATI_V1_ITEMS = 'REQUEST_NATI_V1_ITEMS',
  RECEIVED_NATI_V1_ITEMS = 'REQUEST_NATI_V1_ITEMS',
  BLOCK_TAB = 'BLOCK_TAB',
  UNBLOCK_TAB = 'UNBLOCK_TAB',
  RECEIVED_DESENFILA_PAYMENT = 'RECEIVED_DESENFILA_PAYMENT',
}
