import { EPaymentType, IPaymentProvider } from '../../general';
import { ICustomerInfo } from '../../master-setting';
import { IOrder } from '../../order';
import { EInvoiceStatus } from '../enums';
import { IInvoiceBankSlip } from './i-invoice-bank-slip';
import { IInvoiceCreditCard } from './i-invoice-credit-card';
import { IInvoiceItem } from './i-invoice-item';
import { IInvoiceLog } from './i-invoice-log';
import { IInvoicePix } from './i-invoice-pix';

export interface IInvoice {
  orderId?: string;
  orders?: IOrder[] | null;
  addition: number;
  bankSlip: IInvoiceBankSlip | null;
  bankSlipExtraDue: number;
  createdAt: Date;
  creditCard: IInvoiceCreditCard | null;
  currency: string;
  customerId: string | null;
  discount: number;
  email: string | null;
  externalInvoiceId: string;
  externalInvoiceUrl: string;
  id: string;
  items: IInvoiceItem[];
  logs: IInvoiceLog[];
  notes: string;
  paidAt: Date | null;
  expiresAt: Date | null;
  payer: ICustomerInfo;
  paymentMethod: EPaymentType;
  pix: IInvoicePix | null;
  sandbox: boolean;
  status: EInvoiceStatus;
  subTotal: number;
  subscriptionId: string;
  totalAmount: number;
  totalFee: number;
  totalOverPaid: number;
  totalPaid: number;
  totalRefunded: number;
  updatedAt: Date;
  notificationUrl: string;
  returnUrl: string;
}
