export enum EInstallationStatus {
  INSTALLED = 'INSTALLED',
  ACTIVE = 'ACTIVE',
  CANCELLED = 'CANCELLED',
  PLACED = 'PLACED',
  EXPIRED = 'EXPIRED',
  PENDING = 'PENDING',
  TRIAL = 'TRIAL',
  FREE = 'FREE',
  SUSPENDED = 'SUSPENDED',
}
