export enum EInputTypes {
  /**
   * Assinatura da Franqueadora:
   **/
  ASSINATURA_DA_FRANQUEADORA = 'ASSINATURA_DA_FRANQUEADORA',
  /**
   * Assinatura da Parte 1:
   **/
  ASSINATURA_DA_PARTE_1 = 'ASSINATURA_DA_PARTE_1',
  /**
   * Assinatura da Parte 2:
   **/
  ASSINATURA_DA_PARTE_2 = 'ASSINATURA_DA_PARTE_2',
  /**
   * Assinatura da Permutante 1:
   **/
  ASSINATURA_DA_PERMUTANTE_1 = 'ASSINATURA_DA_PERMUTANTE_1',
  /**
   * Assinatura da Permutante 2:
   **/
  ASSINATURA_DA_PERMUTANTE_2 = 'ASSINATURA_DA_PERMUTANTE_2',
  /**
   * Assinatura da Produtora:
   **/
  ASSINATURA_DA_PRODUTORA = 'ASSINATURA_DA_PRODUTORA',
  /**
   * Assinatura da Representada:
   **/
  ASSINATURA_DA_REPRESENTADA = 'ASSINATURA_DA_REPRESENTADA',
  /**
   * Assinatura da Testemunha:
   **/
  ASSINATURA_DA_TESTEMUNHA = 'ASSINATURA_DA_TESTEMUNHA',
  /**
   * Assinatura do Advogado:
   **/
  ASSINATURA_DO_ADVOGADO = 'ASSINATURA_DO_ADVOGADO',
  /**
   * Assinatura do Aprendiz:
   **/
  ASSINATURA_DO_APRENDIZ = 'ASSINATURA_DO_APRENDIZ',
  /**
   * Assinatura do Colaborador:
   **/
  ASSINATURA_DO_COLABORADOR = 'ASSINATURA_DO_COLABORADOR',
  /**
   * Assinatura do Comissário:
   **/
  ASSINATURA_DO_COMISSÁRIO = 'ASSINATURA_DO_COMISSÁRIO',
  /**
   * Assinatura do Comitente:
   **/
  ASSINATURA_DO_COMITENTE = 'ASSINATURA_DO_COMITENTE',
  /**
   * Assinatura do Comodante:
   **/
  ASSINATURA_DO_COMODANTE = 'ASSINATURA_DO_COMODANTE',
  /**
   * Assinatura do Comodatário:
   **/
  ASSINATURA_DO_COMODATÁRIO = 'ASSINATURA_DO_COMODATÁRIO',
  /**
   * Assinatura do Comprador:
   **/
  ASSINATURA_DO_COMPRADOR = 'ASSINATURA_DO_COMPRADOR',
  /**
   * Assinatura do Concedente:
   **/
  ASSINATURA_DO_CONCEDENTE = 'ASSINATURA_DO_CONCEDENTE',
  /**
   * Assinatura do Contratado:
   **/
  ASSINATURA_DO_CONTRATADO = 'ASSINATURA_DO_CONTRATADO',
  /**
   * Assinatura do Contratante:
   **/
  ASSINATURA_DO_CONTRATANTE = 'ASSINATURA_DO_CONTRATANTE',
  /**
   * Assinatura do Corretor:
   **/
  ASSINATURA_DO_CORRETOR = 'ASSINATURA_DO_CORRETOR',
  /**
   * Assinatura do Credor:
   **/
  ASSINATURA_DO_CREDOR = 'ASSINATURA_DO_CREDOR',
  /**
   * Assinatura do Depositante:
   **/
  ASSINATURA_DO_DEPOSITANTE = 'ASSINATURA_DO_DEPOSITANTE',
  /**
   * Assinatura do Depositário:
   **/
  ASSINATURA_DO_DEPOSITÁRIO = 'ASSINATURA_DO_DEPOSITÁRIO',
  /**
   * Assinatura do Devedor:
   **/
  ASSINATURA_DO_DEVEDOR = 'ASSINATURA_DO_DEVEDOR',
  /**
   * Assinatura do Diretor-Administrativo:
   **/
  ASSINATURA_DO_DIRETOR_ADMINISTRATIVO = 'ASSINATURA_DO_DIRETOR_ADMINISTRATIVO',
  /**
   * Assinatura do Doador:
   **/
  ASSINATURA_DO_DOADOR = 'ASSINATURA_DO_DOADOR',
  /**
   * Assinatura do Donatário:
   **/
  ASSINATURA_DO_DONATÁRIO = 'ASSINATURA_DO_DONATÁRIO',
  /**
   * Assinatura do Empreendedor 1:
   **/
  ASSINATURA_DO_EMPREENDEDOR_1 = 'ASSINATURA_DO_EMPREENDEDOR_1',
  /**
   * Assinatura do Empreendedor 2:
   **/
  ASSINATURA_DO_EMPREENDEDOR_2 = 'ASSINATURA_DO_EMPREENDEDOR_2',
  /**
   * Assinatura do Empregado:
   **/
  ASSINATURA_DO_EMPREGADO = 'ASSINATURA_DO_EMPREGADO',
  /**
   * Assinatura do Estagiário:
   **/
  ASSINATURA_DO_ESTAGIÁRIO = 'ASSINATURA_DO_ESTAGIÁRIO',
  /**
   * Assinatura do Fiador:
   **/
  ASSINATURA_DO_FIADOR = 'ASSINATURA_DO_FIADOR',
  /**
   * Assinatura do Financiado:
   **/
  ASSINATURA_DO_FINANCIADO = 'ASSINATURA_DO_FINANCIADO',
  /**
   * Assinatura do Financiador:
   **/
  ASSINATURA_DO_FINANCIADOR = 'ASSINATURA_DO_FINANCIADOR',
  /**
   * Assinatura do Instituição de Ensino:
   **/
  ASSINATURA_DO_INSTITUIÇÃO_DE_ENSINO = 'ASSINATURA_DO_INSTITUIÇÃO_DE_ENSINO',
  /**
   * Assinatura do Locador:
   **/
  ASSINATURA_DO_LOCADOR = 'ASSINATURA_DO_LOCADOR',
  /**
   * Assinatura do Locatário:
   **/
  ASSINATURA_DO_LOCATÁRIO = 'ASSINATURA_DO_LOCATÁRIO',
  /**
   * Assinatura do Mutuante:
   **/
  ASSINATURA_DO_MUTUANTE = 'ASSINATURA_DO_MUTUANTE',
  /**
   * Assinatura do Mutuário:
   **/
  ASSINATURA_DO_MUTUÁRIO = 'ASSINATURA_DO_MUTUÁRIO',
  /**
   * Assinatura do Outorgante:
   **/
  ASSINATURA_DO_OUTORGANTE = 'ASSINATURA_DO_OUTORGANTE',
  /**
   * Assinatura do Presidente:
   **/
  ASSINATURA_DO_PRESIDENTE = 'ASSINATURA_DO_PRESIDENTE',
  /**
   * Assinatura do Primeiro Permutante:
   **/
  ASSINATURA_DO_PRIMEIRO_PERMUTANTE = 'ASSINATURA_DO_PRIMEIRO_PERMUTANTE',
  /**
   * Assinatura do Representante da Empregadora:
   **/
  ASSINATURA_DO_REPRESENTANTE_DA_EMPREGADORA = 'ASSINATURA_DO_REPRESENTANTE_DA_EMPREGADORA',
  /**
   * Assinatura do Representante:
   **/
  ASSINATURA_DO_REPRESENTANTE = 'ASSINATURA_DO_REPRESENTANTE',
  /**
   * Assinatura do Responsável:
   **/
  ASSINATURA_DO_RESPONSÁVEL = 'ASSINATURA_DO_RESPONSÁVEL',
  /**
   * Assinatura do Secretário:
   **/
  ASSINATURA_DO_SECRETÁRIO = 'ASSINATURA_DO_SECRETÁRIO',
  /**
   * Assinatura do Segundo Permutante:
   **/
  ASSINATURA_DO_SEGUNDO_PERMUTANTE = 'ASSINATURA_DO_SEGUNDO_PERMUTANTE',
  /**
   * Assinatura do Sócio:
   **/
  ASSINATURA_DO_SÓCIO = 'ASSINATURA_DO_SÓCIO',
  /**
   * Assinatura do Vendedor:
   **/
  ASSINATURA_DO_VENDEDOR = 'ASSINATURA_DO_VENDEDOR',
  /**
   * Assinatura do(a) Requerente:
   **/
  ASSINATURA_DO_A_REQUERENTE = 'ASSINATURA_DO_A_REQUERENTE',
  /**
   * Assinatura dos Sócios:
   **/
  ASSINATURA_DOS_SÓCIOS = 'ASSINATURA_DOS_SÓCIOS',
  /**
   * Assistente de acusação: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  ASSISTENTE_DE_ACUSAÇÃO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'ASSISTENTE_DE_ACUSAÇÃO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Atividades do Empreendedor:
   **/
  ATIVIDADES_DO_EMPREENDEDOR = 'ATIVIDADES_DO_EMPREENDEDOR',
  /**
   * Autor: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  AUTOR_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'AUTOR_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Banco emissor da carta de crédito: NOME DO BANCO, AGÊNCIA
   **/
  BANCO_EMISSOR_DA_CARTA_DE_CRÉDITO_NOME_DO_BANCO_AGÊNCIA = 'BANCO_EMISSOR_DA_CARTA_DE_CRÉDITO_NOME_DO_BANCO_AGÊNCIA',
  /**
   * Banco/agência:
   **/
  BANCO_AGÊNCIA = 'BANCO_AGÊNCIA',
  /**
   * Bem alienado: Elementos indispensáveis à sua perfeita identificação
   **/
  BEM_ALIENADO_ELEMENTOS_INDISPENSÁVEIS_À_SUA_PERFEITA_IDENTIFICAÇÃO = 'BEM_ALIENADO_ELEMENTOS_INDISPENSÁVEIS_À_SUA_PERFEITA_IDENTIFICAÇÃO',
  /**
   * Caracterização do veículo: MARCA, MODELO, PLACA, ANO
   **/
  CARACTERIZAÇÃO_DO_VEÍCULO_MARCA_MODELO_PLACA_ANO = 'CARACTERIZAÇÃO_DO_VEÍCULO_MARCA_MODELO_PLACA_ANO',
  /**
   * Carga horária semanal:
   **/
  CARGA_HORÁRIA_SEMANAL = 'CARGA_HORÁRIA_SEMANAL',
  /**
   * Cargo/Função do Empregado:
   **/
  CARGO_FUNÇÃO_DO_EMPREGADO = 'CARGO_FUNÇÃO_DO_EMPREGADO',
  /**
   * Cargo/Função:
   **/
  CARGO_FUNÇÃO = 'CARGO_FUNÇÃO',
  /**
   * Cedente: Razão Social, Endereço da sede, nº CNPJ
   **/
  CEDENTE_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'CEDENTE_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Cessionária: Razão Social, Endereço da sede, nº CNPJ
   **/
  CESSIONÁRIA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'CESSIONÁRIA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Cheque nº:
   **/
  CHEQUE_Nº = 'CHEQUE_Nº',
  /**
   * Clausulas
   **/
  CLAUSULAS = 'CLAUSULAS',
  /**
   * Colaborador: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  COLABORADOR_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'COLABORADOR_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Comissário: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  COMISSÁRIO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'COMISSÁRIO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Comitente: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  COMITENTE_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'COMITENTE_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Comodatário: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  COMODATÁRIO_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'COMODATÁRIO_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Composição da Mesa:
   **/
  COMPOSIÇÃO_DA_MESA = 'COMPOSIÇÃO_DA_MESA',
  /**
   * Comprador (Pessoa Física): NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  COMPRADOR_PESSOA_FÍSICA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'COMPRADOR_PESSOA_FÍSICA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Comprador (Pessoa Jurídica): Razão Social, Endereço da sede, nº CNPJ
   **/
  COMPRADOR_PESSOA_JURÍDICA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'COMPRADOR_PESSOA_JURÍDICA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Concente: Razão Social, Endereço da sede, nº CNPJ
   **/
  CONCENTE_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'CONCENTE_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Confidente devedora: Razão Social, Endereço da sede, nº CNPJ
   **/
  CONFIDENTE_DEVEDORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'CONFIDENTE_DEVEDORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Consignante: Razão Social, Endereço da sede, nº CNPJ
   **/
  CONSIGNANTE_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'CONSIGNANTE_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Consignatário: Razão Social, Endereço da sede, nº CNPJ
   **/
  CONSIGNATÁRIO_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'CONSIGNATÁRIO_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Contra-prestação pela licença (percentual):
   **/
  CONTRA_PRESTAÇÃO_PELA_LICENÇA_PERCENTUAL = 'CONTRA_PRESTAÇÃO_PELA_LICENÇA_PERCENTUAL',
  /**
   * Contratada (Pessoa Física): NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  CONTRATADA_PESSOA_FÍSICA_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'CONTRATADA_PESSOA_FÍSICA_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Contratada (Pessoa Jurídica): Razão Social, Endereço da sede, nº CNPJ
   **/
  CONTRATADA_PESSOA_JURÍDICA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'CONTRATADA_PESSOA_JURÍDICA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Contratado: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  CONTRATADO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'CONTRATADO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Contratante (Pessoa Física): NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  CONTRATANTE_PESSOA_FÍSICA_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'CONTRATANTE_PESSOA_FÍSICA_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Contratante (Pessoa Jurídica): Razão Social, Endereço da sede, nº CNPJ
   **/
  CONTRATANTE_PESSOA_JURÍDICA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'CONTRATANTE_PESSOA_JURÍDICA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Corretor: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  CORRETOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'CORRETOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Credor: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  CREDOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'CREDOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Custos adicionais: DISPOR COMO SERÃO REEMBOLSADOS
   **/
  CUSTOS_ADICIONAIS_DISPOR_COMO_SERÃO_REEMBOLSADOS = 'CUSTOS_ADICIONAIS_DISPOR_COMO_SERÃO_REEMBOLSADOS',
  /**
   * Dados da Duplicata
   **/
  DADOS_DA_DUPLICATA = 'DADOS_DA_DUPLICATA',
  /**
   * Dados da Empresa: 
   **/
  DADOS_DA_EMPRESA = 'DADOS_DA_EMPRESA',
  /**
   * Dados da Sociedade: Nome Empresarial,/Firma/ Denominação, nº CNPJ
   **/
  DADOS_DA_SOCIEDADE_NOME_EMPRESARIAL_FIRMA_DENOMINAÇÃO_Nº_CNPJ = 'DADOS_DA_SOCIEDADE_NOME_EMPRESARIAL_FIRMA_DENOMINAÇÃO_Nº_CNPJ',
  /**
   * Dados do bem alienado: descrição (cor, ano, modelo, tamanho, etc)
   **/
  DADOS_DO_BEM_ALIENADO_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC = 'DADOS_DO_BEM_ALIENADO_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC',
  /**
   * Dados do bem depositado: descrição (cor, ano, modelo, tamanho, etc)
   **/
  DADOS_DO_BEM_DEPOSITADO_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC = 'DADOS_DO_BEM_DEPOSITADO_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC',
  /**
   * Dados do bem locado: tipo do bem (móvel, imóvel), descrição (cor, ano, modelo, tamanho, etc)/ e/ou endereço do imóvel
   **/
  DADOS_DO_BEM_LOCADO_TIPO_DO_BEM_MÓVEL_IMÓVEL_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC_E_OU_ENDEREÇO_DO_IMÓVEL = 'DADOS_DO_BEM_LOCADO_TIPO_DO_BEM_MÓVEL_IMÓVEL_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC_E_OU_ENDEREÇO_DO_IMÓVEL',
  /**
   * Dados do bem mutuado: descrição (cor, ano, modelo, tamanho, etc)
   **/
  DADOS_DO_BEM_MUTUADO_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC = 'DADOS_DO_BEM_MUTUADO_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC',
  /**
   * Dados do bem: descrição do bem, quantidade, qualidade, valor estimado
   **/
  DADOS_DO_BEM_DESCRIÇÃO_DO_BEM_QUANTIDADE_QUALIDADE_VALOR_ESTIMADO = 'DADOS_DO_BEM_DESCRIÇÃO_DO_BEM_QUANTIDADE_QUALIDADE_VALOR_ESTIMADO',
  /**
   * Dados dos bens: tipo do bem (móvel, imóvel), descrição (cor, ano, modelo, tamanho, etc)/ e/ou endereço do imóvel
   **/
  DADOS_DOS_BENS_TIPO_DO_BEM_MÓVEL_IMÓVEL_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC_E_OU_ENDEREÇO_DO_IMÓVEL = 'DADOS_DOS_BENS_TIPO_DO_BEM_MÓVEL_IMÓVEL_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC_E_OU_ENDEREÇO_DO_IMÓVEL',
  /**
   * Dados para cumprir as formalidades da rescisão: Local, Data, Horário
   **/
  DADOS_PARA_CUMPRIR_AS_FORMALIDADES_DA_RESCISÃO_LOCAL_DATA_HORÁRIO = 'DADOS_PARA_CUMPRIR_AS_FORMALIDADES_DA_RESCISÃO_LOCAL_DATA_HORÁRIO',
  /**
   * Data de início do contrato:
   **/
  DATA_DE_INÍCIO_DO_CONTRATO = 'DATA_DE_INÍCIO_DO_CONTRATO',
  /**
   * Data de início:
   **/
  DATA_DE_INÍCIO = 'DATA_DE_INÍCIO',
  /**
   * Data de recebimento da remuneração:
   **/
  DATA_DE_RECEBIMENTO_DA_REMUNERAÇÃO = 'DATA_DE_RECEBIMENTO_DA_REMUNERAÇÃO',
  /**
   * Data de término do contrato:
   **/
  DATA_DE_TÉRMINO_DO_CONTRATO = 'DATA_DE_TÉRMINO_DO_CONTRATO',
  /**
   * Data, hora e local: DD de MM de YYYY, às Z horas, na empresa X, endereço
   **/
  DATA_HORA_E_LOCAL_DD_DE_MM_DE_YYYY_ÀS_Z_HORAS_NA_EMPRESA_X_ENDEREÇO = 'DATA_HORA_E_LOCAL_DD_DE_MM_DE_YYYY_ÀS_Z_HORAS_NA_EMPRESA_X_ENDEREÇO',
  /**
   * De cujus (Autor da herança): NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  DE_CUJUS_AUTOR_DA_HERANÇA_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'DE_CUJUS_AUTOR_DA_HERANÇA_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Denominação:
   **/
  DENOMINAÇÃO = 'DENOMINAÇÃO',
  /**
   * Depositante: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  DEPOSITANTE_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'DEPOSITANTE_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Depositário: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  DEPOSITÁRIO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'DEPOSITÁRIO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Depto/Setor do Empregador:
   **/
  DEPTO_SETOR_DO_EMPREGADOR = 'DEPTO_SETOR_DO_EMPREGADOR',
  /**
   * Devedor: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  DEVEDOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'DEVEDOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Dia(s) e horário(s) da prestação do serviço:
   **/
  DIA_S_E_HORÁRIO_S_DA_PRESTAÇÃO_DO_SERVIÇO = 'DIA_S_E_HORÁRIO_S_DA_PRESTAÇÃO_DO_SERVIÇO',
  /**
   * Discriminação dos produtos:
   **/
  DISCRIMINAÇÃO_DOS_PRODUTOS = 'DISCRIMINAÇÃO_DOS_PRODUTOS',
  /**
   * Distribuidora: Razão Social, Endereço da sede, nº CNPJ
   **/
  DISTRIBUIDORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'DISTRIBUIDORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Doador: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  DOADOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'DOADOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Donatário: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  DONATÁRIO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'DONATÁRIO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Embargado: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  EMBARGADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'EMBARGADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Embargante: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  EMBARGANTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'EMBARGANTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Empreendedor: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  EMPREENDEDOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'EMPREENDEDOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Empregado: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  EMPREGADO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'EMPREGADO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Empregadora: Razão Social, Endereço da sede, nº CNPJ
   **/
  EMPREGADORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'EMPREGADORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Empresa: Razão Social
   **/
  EMPRESA_RAZÃO_SOCIAL = 'EMPRESA_RAZÃO_SOCIAL',
  /**
   * Endereçamento: Delegado de Polícia, Promotor de Justiça, Juiz de Direito
   **/
  ENDEREÇAMENTO_DELEGADO_DE_POLÍCIA_PROMOTOR_DE_JUSTIÇA_JUIZ_DE_DIREITO = 'ENDEREÇAMENTO_DELEGADO_DE_POLÍCIA_PROMOTOR_DE_JUSTIÇA_JUIZ_DE_DIREITO',
  /**
   * Endereço da sede da sociedade:
   **/
  ENDEREÇO_DA_SEDE_DA_SOCIEDADE = 'ENDEREÇO_DA_SEDE_DA_SOCIEDADE',
  /**
   * Endereço:
   **/
  ENDEREÇO = 'ENDEREÇO',
  /**
   * Estagiário: Financiado: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  ESTAGIÁRIO_FINANCIADO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'ESTAGIÁRIO_FINANCIADO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Excepto: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  EXCEPTO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'EXCEPTO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Excipiente: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  EXCIPIENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'EXCIPIENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Executado: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  EXECUTADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'EXECUTADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Exequente: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  EXEQUENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'EXEQUENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Faltas: breve descrição das faltas (detalhar melhor na seção "FATOS")
   **/
  FALTAS_BREVE_DESCRIÇÃO_DAS_FALTAS_DETALHAR_MELHOR_NA_SEÇÃO_FATOS = 'FALTAS_BREVE_DESCRIÇÃO_DAS_FALTAS_DETALHAR_MELHOR_NA_SEÇÃO_FATOS',
  /**
   * Faturizada: Razão Social, Endereço da sede, nº CNPJ
   **/
  FATURIZADA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'FATURIZADA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Faturizadora: Razão Social, Endereço da sede, nº CNPJ
   **/
  FATURIZADORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'FATURIZADORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Fiador: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  FIADOR_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'FIADOR_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Fim da procuração:
   **/
  FIM_DA_PROCURAÇÃO = 'FIM_DA_PROCURAÇÃO',
  /**
   * Fim das atividades (se couber)
   **/
  FIM_DAS_ATIVIDADES_SE_COUBER = 'FIM_DAS_ATIVIDADES_SE_COUBER',
  /**
   * Financiado (Pessoa Física): NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  FINANCIADO_PESSOA_FÍSICA_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'FINANCIADO_PESSOA_FÍSICA_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Financiado(Pessoa Jurídica): Razão Social, Endereço da sede, nº CNPJ
   **/
  FINANCIADO_PESSOA_JURÍDICA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'FINANCIADO_PESSOA_JURÍDICA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Financiador: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  FINANCIADOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'FINANCIADOR_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Financiadora: Razão Social, Endereço da sede, nº CNPJ
   **/
  FINANCIADORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'FINANCIADORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Foro Consultivo: Comarca do Município
   **/
  FORO_CONSULTIVO_COMARCA_DO_MUNICÍPIO = 'FORO_CONSULTIVO_COMARCA_DO_MUNICÍPIO',
  /**
   * Foro Contencioso: VARA, JUSTIÇA FEDERAL, JUSTIÇA ESTADUAL
   **/
  FORO_CONTENCIOSO_VARA_JUSTIÇA_FEDERAL_JUSTIÇA_ESTADUAL = 'FORO_CONTENCIOSO_VARA_JUSTIÇA_FEDERAL_JUSTIÇA_ESTADUAL',
  /**
   * Franqueada: Razão Social, Endereço da sede, nº CNPJ
   **/
  FRANQUEADA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'FRANQUEADA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Franqueadora: Razão Social, Endereço da sede, nº CNPJ
   **/
  FRANQUEADORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'FRANQUEADORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Herdeiro: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  HERDEIRO_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'HERDEIRO_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Impetrado: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  IMPETRADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'IMPETRADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Impetrado (Órgão Público): NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA, NOME DA PESSOA JURÍDICA
   **/
  IMPETRADO_ÓRGÃO_PÚBLICO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA_NOME_DA_PESSOA_JURÍDICA = 'IMPETRADO_ÓRGÃO_PÚBLICO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA_NOME_DA_PESSOA_JURÍDICA',
  /**
   * Impetrante: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  IMPETRANTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'IMPETRANTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Impetrante Habeas Corpus: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA, nome do paciente
   **/
  IMPETRANTE_HABEAS_CORPUS_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA_NOME_DO_PACIENTE = 'IMPETRANTE_HABEAS_CORPUS_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA_NOME_DO_PACIENTE',
  /**
   * Índice de correção monetária:
   **/
  ÍNDICE_DE_CORREÇÃO_MONETÁRIA = 'ÍNDICE_DE_CORREÇÃO_MONETÁRIA',
  /**
   * Início das atividades:
   **/
  INÍCIO_DAS_ATIVIDADES = 'INÍCIO_DAS_ATIVIDADES',
  /**
   * Instituição de Ensino:
   **/
  INSTITUIÇÃO_DE_ENSINO = 'INSTITUIÇÃO_DE_ENSINO',
  /**
   * Interditando: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  INTERDITANDO_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'INTERDITANDO_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Jornada: X h às Y h
   **/
  JORNADA_X_H_ÀS_Y_H = 'JORNADA_X_H_ÀS_Y_H',
  /**
   * Juros:
   **/
  JUROS = 'JUROS',
  /**
   * Legitimado ativo: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  LEGITIMADO_ATIVO_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'LEGITIMADO_ATIVO_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Legitimado passivo: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  LEGITIMADO_PASSIVO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'LEGITIMADO_PASSIVO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Licenciado: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  LICENCIADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'LICENCIADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Licenciante: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  LICENCIANTE_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'LICENCIANTE_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Locador: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  LOCADOR_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'LOCADOR_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Local de trabalho:
   **/
  LOCAL_DE_TRABALHO = 'LOCAL_DE_TRABALHO',
  /**
   * Local e data: CIDADE, DD de MM de YYYY
   **/
  LOCAL_E_DATA_CIDADE_DD_DE_MM_DE_YYYY = 'LOCAL_E_DATA_CIDADE_DD_DE_MM_DE_YYYY',
  /**
   * Locatário: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  LOCATÁRIO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'LOCATÁRIO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Marca:
   **/
  MARCA = 'MARCA',
  /**
   * Mutuante: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  MUTUANTE_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'MUTUANTE_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Mutuário: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  MUTUÁRIO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'MUTUÁRIO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Nº da ação:
   **/
  Nº_DA_AÇÃO = 'Nº_DA_AÇÃO',
  /**
   * Nº de parcelas:
   **/
  Nº_DE_PARCELAS = 'Nº_DE_PARCELAS',
  /**
   * Nº de vales:
   **/
  Nº_DE_VALES = 'Nº_DE_VALES',
  /**
   * Nome do sócio administrador:
   **/
  NOME_DO_SÓCIO_ADMINISTRADOR = 'NOME_DO_SÓCIO_ADMINISTRADOR',
  /**
   * Nome do sócio/qtde de quotas/ valor a ser integralizado por ele:
   **/
  NOME_DO_SÓCIO_QTDE_DE_QUOTAS_VALOR_A_SER_INTEGRALIZADO_POR_ELE = 'NOME_DO_SÓCIO_QTDE_DE_QUOTAS_VALOR_A_SER_INTEGRALIZADO_POR_ELE',
  /**
   * Nome empresarial:
   **/
  NOME_EMPRESARIAL = 'NOME_EMPRESARIAL',
  /**
   * OAB nº:
   **/
  OAB_Nº = 'OAB_Nº',
  /**
   * Objeto da sociedade:
   **/
  OBJETO_DA_SOCIEDADE = 'OBJETO_DA_SOCIEDADE',
  /**
   * Objeto do contrato:
   **/
  OBJETO_DO_CONTRATO = 'OBJETO_DO_CONTRATO',
  /**
   * Objeto:
   **/
  OBJETO = 'OBJETO',
  /**
   * Objeto: obra, endereço da obra. (OBS: Descreva o cronograma na seção "FATOS") - dev/designer colocar esse lembrete
   **/
  OBJETO_OBRA_ENDEREÇO_DA_OBRA_OBS_DESCREVA_O_CRONOGRAMA_NA_SEÇÃO_FATOS_DEV_DESIGNER_COLOCAR_ESSE_LEMBRETE = 'OBJETO_OBRA_ENDEREÇO_DA_OBRA_OBS_DESCREVA_O_CRONOGRAMA_NA_SEÇÃO_FATOS_DEV_DESIGNER_COLOCAR_ESSE_LEMBRETE',
  /**
   * Objeto: tipo do bem (se móvel ou imóvel), descrição (cor, ano, modelo, tamanho, etc)
   **/
  OBJETO_TIPO_DO_BEM_SE_MÓVEL_OU_IMÓVEL_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC = 'OBJETO_TIPO_DO_BEM_SE_MÓVEL_OU_IMÓVEL_DESCRIÇÃO_COR_ANO_MODELO_TAMANHO_ETC',
  /**
   * Opção pela audiência de conciliação: Sim/Não
   **/
  OPÇÃO_PELA_AUDIÊNCIA_DE_CONCILIAÇÃO_SIM_NÃO = 'OPÇÃO_PELA_AUDIÊNCIA_DE_CONCILIAÇÃO_SIM_NÃO',
  /**
   * Opoente: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  OPOENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'OPOENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Ordem do dia:
   **/
  ORDEM_DO_DIA = 'ORDEM_DO_DIA',
  /**
   * Origem do débito:
   **/
  ORIGEM_DO_DÉBITO = 'ORIGEM_DO_DÉBITO',
  /**
   * Origem: VARA, JUSTIÇA FEDERAL, JUSTIÇA ESTADUAL
   **/
  ORIGEM_VARA_JUSTIÇA_FEDERAL_JUSTIÇA_ESTADUAL = 'ORIGEM_VARA_JUSTIÇA_FEDERAL_JUSTIÇA_ESTADUAL',
  /**
   * Outorgado (Procurador): NOME, NACIONALIDADE, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, nº OAB, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  OUTORGADO_PROCURADOR_NOME_NACIONALIDADE_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_Nº_OAB_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'OUTORGADO_PROCURADOR_NOME_NACIONALIDADE_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_Nº_OAB_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Outorgante: NOME, NACIONALIDADE, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  OUTORGANTE_NOME_NACIONALIDADE_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'OUTORGANTE_NOME_NACIONALIDADE_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Paciente: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  PACIENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'PACIENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Pagamento (aprovação final do sistema): DISPOR DA FORMA, SE EM PARCELAS, POR PRODUTIVIDADE, POR ENTREGÁVEL, SE VIACHEQUE/BOLETO BANCÁRIO/PIX
   **/
  PAGAMENTO_APROVAÇÃO_FINAL_DO_SISTEMA_DISPOR_DA_FORMA_SE_EM_PARCELAS_POR_PRODUTIVIDADE_POR_ENTREGÁVEL_SE_VIACHEQUE_BOLETO_BANCÁRIO_PIX = 'PAGAMENTO_APROVAÇÃO_FINAL_DO_SISTEMA_DISPOR_DA_FORMA_SE_EM_PARCELAS_POR_PRODUTIVIDADE_POR_ENTREGÁVEL_SE_VIACHEQUE_BOLETO_BANCÁRIO_PIX',
  /**
   * Pagamento (conclusão): DISPOR DA FORMA, SE EM PARCELAS, POR PRODUTIVIDADE, POR ENTREGÁVEL, SE VIACHEQUE/BOLETO BANCÁRIO/PIX
   **/
  PAGAMENTO_CONCLUSÃO_DISPOR_DA_FORMA_SE_EM_PARCELAS_POR_PRODUTIVIDADE_POR_ENTREGÁVEL_SE_VIACHEQUE_BOLETO_BANCÁRIO_PIX = 'PAGAMENTO_CONCLUSÃO_DISPOR_DA_FORMA_SE_EM_PARCELAS_POR_PRODUTIVIDADE_POR_ENTREGÁVEL_SE_VIACHEQUE_BOLETO_BANCÁRIO_PIX',
  /**
   * Pagamento (início da execução): DISPOR DA FORMA, SE EM PARCELAS, POR PRODUTIVIDADE, POR ENTREGÁVEL, SE VIACHEQUE/BOLETO BANCÁRIO/PIX
   **/
  PAGAMENTO_INÍCIO_DA_EXECUÇÃO_DISPOR_DA_FORMA_SE_EM_PARCELAS_POR_PRODUTIVIDADE_POR_ENTREGÁVEL_SE_VIACHEQUE_BOLETO_BANCÁRIO_PIX = 'PAGAMENTO_INÍCIO_DA_EXECUÇÃO_DISPOR_DA_FORMA_SE_EM_PARCELAS_POR_PRODUTIVIDADE_POR_ENTREGÁVEL_SE_VIACHEQUE_BOLETO_BANCÁRIO_PIX',
  /**
   * Pagamento (valor total):
   **/
  PAGAMENTO_VALOR_TOTAL = 'PAGAMENTO_VALOR_TOTAL',
  /**
   * Pagamento:
   **/
  PAGAMENTO = 'PAGAMENTO',
  /**
   * Parte 1 (Quem pagará a indenização)
   **/
  PARTE_1_QUEM_PAGARÁ_A_INDENIZAÇÃO = 'PARTE_1_QUEM_PAGARÁ_A_INDENIZAÇÃO',
  /**
   * Parte 2 (Quem receberá a indenização)
   **/
  PARTE_2_QUEM_RECEBERÁ_A_INDENIZAÇÃO = 'PARTE_2_QUEM_RECEBERÁ_A_INDENIZAÇÃO',
  /**
   * Período da parceria:
   **/
  PERÍODO_DA_PARCERIA = 'PERÍODO_DA_PARCERIA',
  /**
   * Período referente ao recebimento: Semana/Mês/Ano
   **/
  PERÍODO_REFERENTE_AO_RECEBIMENTO_SEMANA_MÊS_ANO = 'PERÍODO_REFERENTE_AO_RECEBIMENTO_SEMANA_MÊS_ANO',
  /**
   * Permutante 1: Razão Social, Endereço da sede, nº CNPJ
   **/
  PERMUTANTE_1_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'PERMUTANTE_1_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Permutante 2: Razão Social, Endereço da sede, nº CNPJ
   **/
  PERMUTANTE_2_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'PERMUTANTE_2_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Prazo da suspensão do contrato:
   **/
  PRAZO_DA_SUSPENSÃO_DO_CONTRATO = 'PRAZO_DA_SUSPENSÃO_DO_CONTRATO',
  /**
   * Prazo de notificação aos clientes acerca da cessão de crédito:
   **/
  PRAZO_DE_NOTIFICAÇÃO_AOS_CLIENTES_ACERCA_DA_CESSÃO_DE_CRÉDITO = 'PRAZO_DE_NOTIFICAÇÃO_AOS_CLIENTES_ACERCA_DA_CESSÃO_DE_CRÉDITO',
  /**
   * Prazo do contrato:
   **/
  PRAZO_DO_CONTRATO = 'PRAZO_DO_CONTRATO',
  /**
   * Prazo para liquidação de créditos:
   **/
  PRAZO_PARA_LIQUIDAÇÃO_DE_CRÉDITOS = 'PRAZO_PARA_LIQUIDAÇÃO_DE_CRÉDITOS',
  /**
   * Prazo para o desenvolvimento do sistema:
   **/
  PRAZO_PARA_O_DESENVOLVIMENTO_DO_SISTEMA = 'PRAZO_PARA_O_DESENVOLVIMENTO_DO_SISTEMA',
  /**
   * Prazo para opção de compra:
   **/
  PRAZO_PARA_OPÇÃO_DE_COMPRA = 'PRAZO_PARA_OPÇÃO_DE_COMPRA',
  /**
   * Prazo para pagamento da parcela:
   **/
  PRAZO_PARA_PAGAMENTO_DA_PARCELA = 'PRAZO_PARA_PAGAMENTO_DA_PARCELA',
  /**
   * Prazo para pagamento da remuneração:
   **/
  PRAZO_PARA_PAGAMENTO_DA_REMUNERAÇÃO = 'PRAZO_PARA_PAGAMENTO_DA_REMUNERAÇÃO',
  /**
   * Prazo para pagamento das prestações mensais:
   **/
  PRAZO_PARA_PAGAMENTO_DAS_PRESTAÇÕES_MENSAIS = 'PRAZO_PARA_PAGAMENTO_DAS_PRESTAÇÕES_MENSAIS',
  /**
   * Prazo para pagamento:
   **/
  PRAZO_PARA_PAGAMENTO = 'PRAZO_PARA_PAGAMENTO',
  /**
   * Prazo para rescisão contratual:
   **/
  PRAZO_PARA_RESCISÃO_CONTRATUAL = 'PRAZO_PARA_RESCISÃO_CONTRATUAL',
  /**
   * Prazo para rescisão:
   **/
  PRAZO_PARA_RESCISÃO = 'PRAZO_PARA_RESCISÃO',
  /**
   * Primeiro Permutante:
   **/
  PRIMEIRO_PERMUTANTE = 'PRIMEIRO_PERMUTANTE',
  /**
   * Produto:
   **/
  PRODUTO = 'PRODUTO',
  /**
   * Produtora: Razão Social, Endereço da sede, nº CNPJ
   **/
  PRODUTORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'PRODUTORA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Publicações: Diário Oficial/Jornal X
   **/
  PUBLICAÇÕES_DIÁRIO_OFICIAL_JORNAL_X = 'PUBLICAÇÕES_DIÁRIO_OFICIAL_JORNAL_X',
  /**
   * Qtde de membros no Conselho Fiscal:
   **/
  QTDE_DE_MEMBROS_NO_CONSELHO_FISCAL = 'QTDE_DE_MEMBROS_NO_CONSELHO_FISCAL',
  /**
   * Qtde de quotas/ações:
   **/
  QTDE_DE_QUOTAS_AÇÕES = 'QTDE_DE_QUOTAS_AÇÕES',
  /**
   * Quantia emitida na carta de crédito:
   **/
  QUANTIA_EMITIDA_NA_CARTA_DE_CRÉDITO = 'QUANTIA_EMITIDA_NA_CARTA_DE_CRÉDITO',
  /**
   * Queralado: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  QUERALADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'QUERALADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Queralante: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  QUERALANTE_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'QUERALANTE_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Reclamado: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  RECLAMADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'RECLAMADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Reclamante: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  RECLAMANTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'RECLAMANTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Recorrente: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  RECORRENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'RECORRENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Recorrido: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  RECORRIDO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'RECORRIDO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Remuneração dos diretores:
   **/
  REMUNERAÇÃO_DOS_DIRETORES = 'REMUNERAÇÃO_DOS_DIRETORES',
  /**
   * Remuneração para o Empreendedor 1:
   **/
  REMUNERAÇÃO_PARA_O_EMPREENDEDOR_1 = 'REMUNERAÇÃO_PARA_O_EMPREENDEDOR_1',
  /**
   * Remuneração para o Empreendedor 12
   **/
  REMUNERAÇÃO_PARA_O_EMPREENDEDOR_12 = 'REMUNERAÇÃO_PARA_O_EMPREENDEDOR_12',
  /**
   * Remuneração:
   **/
  REMUNERAÇÃO = 'REMUNERAÇÃO',
  /**
   * Representada: Razão Social, Endereço da sede, nº CNPJ
   **/
  REPRESENTADA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ = 'REPRESENTADA_RAZÃO_SOCIAL_ENDEREÇO_DA_SEDE_Nº_CNPJ',
  /**
   * Representante da Arrendadora: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_ARRENDADORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_ARRENDADORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Arrendatária: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_ARRENDATÁRIA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_ARRENDATÁRIA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Cedente: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_CEDENTE_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_CEDENTE_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Cessionária: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_CESSIONÁRIA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_CESSIONÁRIA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Confidente devedora:NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_CONFIDENTE_DEVEDORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_CONFIDENTE_DEVEDORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Contratada: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_CONTRATADA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_CONTRATADA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Contratante: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_CONTRATANTE_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_CONTRATANTE_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Distribuidora: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_DISTRIBUIDORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_DISTRIBUIDORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Empregadora: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_EMPREGADORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_EMPREGADORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Faturizada: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_FATURIZADA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_FATURIZADA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Faturizadora: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_FATURIZADORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_FATURIZADORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Financiadora: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_FINANCIADORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_FINANCIADORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Franqueadora: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_FRANQUEADORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_FRANQUEADORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Licenciada: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_LICENCIADA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_LICENCIADA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Licenciante: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_LICENCIANTE_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_LICENCIANTE_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante da Produtora: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DA_PRODUTORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DA_PRODUTORA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante de Franqueada: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DE_FRANQUEADA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DE_FRANQUEADA_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante do Empreendedor 1: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DO_EMPREENDEDOR_1_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DO_EMPREENDEDOR_1_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante do Empreendedor 2: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DO_EMPREENDEDOR_2_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DO_EMPREENDEDOR_2_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante do Financiado: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_DO_FINANCIADO_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_DO_FINANCIADO_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Representante: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REPRESENTANTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REPRESENTANTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Requerente: NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ,NOME DA MÃE COMPLETO, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REQUERENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REQUERENTE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_NOME_DA_MÃE_COMPLETO_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Requerido: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  REQUERIDO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'REQUERIDO_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Responsável: NOME, ESTADO CIVIL, NACIONALIDADE, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  RESPONSÁVEL_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'RESPONSÁVEL_NOME_ESTADO_CIVIL_NACIONALIDADE_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Réu: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  RÉU_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'RÉU_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Rol de testemunhas: NOME, PROFISSÃO, REDIÊNCIA
   **/
  ROL_DE_TESTEMUNHAS_NOME_PROFISSÃO_REDIÊNCIA = 'ROL_DE_TESTEMUNHAS_NOME_PROFISSÃO_REDIÊNCIA',
  /**
   * Segundo Permutante: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  SEGUNDO_PERMUTANTE_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'SEGUNDO_PERMUTANTE_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Sócios:
   **/
  SÓCIOS = 'SÓCIOS',
  /**
   * Temas
   **/
  TEMAS = 'TEMAS',
  /**
   * Testemunhado: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  TESTEMUNHADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'TESTEMUNHADO_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Testemunhante: NOME, ESTADO CIVIL, PROFISSÃO, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO, RESIDÊNCIA
   **/
  TESTEMUNHANTE_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA = 'TESTEMUNHANTE_NOME_ESTADO_CIVIL_PROFISSÃO_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_RESIDÊNCIA',
  /**
   * Trajeto:
   **/
  TRAJETO = 'TRAJETO',
  /**
   * Tribunal: STF, STJ, TRF, TJ
   **/
  TRIBUNAL_STF_STJ_TRF_TJ = 'TRIBUNAL_STF_STJ_TRF_TJ',
  /**
   * Valor da causa:
   **/
  VALOR_DA_CAUSA = 'VALOR_DA_CAUSA',
  /**
   * Valor da dívida:
   **/
  VALOR_DA_DÍVIDA = 'VALOR_DA_DÍVIDA',
  /**
   * Valor da duplicata:
   **/
  VALOR_DA_DUPLICATA = 'VALOR_DA_DUPLICATA',
  /**
   * Valor da opção de compra:
   **/
  VALOR_DA_OPÇÃO_DE_COMPRA = 'VALOR_DA_OPÇÃO_DE_COMPRA',
  /**
   * Valor da parcela:
   **/
  VALOR_DA_PARCELA = 'VALOR_DA_PARCELA',
  /**
   * Valor da primeira parcela:
   **/
  VALOR_DA_PRIMEIRA_PARCELA = 'VALOR_DA_PRIMEIRA_PARCELA',
  /**
   * Valor da Remuneração:
   **/
  VALOR_DA_REMUNERAÇÃO = 'VALOR_DA_REMUNERAÇÃO',
  /**
   * Valor das prestações mensais:
   **/
  VALOR_DAS_PRESTAÇÕES_MENSAIS = 'VALOR_DAS_PRESTAÇÕES_MENSAIS',
  /**
   * Valor de "torna"
   **/
  VALOR_DE_TORNA = 'VALOR_DE_TORNA',
  /**
   * Valor de cada parcela:
   **/
  VALOR_DE_CADA_PARCELA = 'VALOR_DE_CADA_PARCELA',
  /**
   * Valor de cada quota/ação:
   **/
  VALOR_DE_CADA_QUOTA_AÇÃO = 'VALOR_DE_CADA_QUOTA_AÇÃO',
  /**
   * Valor de cada vale:
   **/
  VALOR_DE_CADA_VALE = 'VALOR_DE_CADA_VALE',
  /**
   * Valor de caução dos diretores:
   **/
  VALOR_DE_CAUÇÃO_DOS_DIRETORES = 'VALOR_DE_CAUÇÃO_DOS_DIRETORES',
  /**
   * Valor do bem:
   **/
  VALOR_DO_BEM = 'VALOR_DO_BEM',
  /**
   * Valor do capital social:
   **/
  VALOR_DO_CAPITAL_SOCIAL = 'VALOR_DO_CAPITAL_SOCIAL',
  /**
   * Valor do cheque:
   **/
  VALOR_DO_CHEQUE = 'VALOR_DO_CHEQUE',
  /**
   * Valor do Pagamento:
   **/
  VALOR_DO_PAGAMENTO = 'VALOR_DO_PAGAMENTO',
  /**
   * Valor estimado:
   **/
  VALOR_ESTIMADO = 'VALOR_ESTIMADO',
  /**
   * Valor pago pelo bem:
   **/
  VALOR_PAGO_PELO_BEM = 'VALOR_PAGO_PELO_BEM',
  /**
   * Valor total da venda:
   **/
  VALOR_TOTAL_DA_VENDA = 'VALOR_TOTAL_DA_VENDA',
  /**
   * Valor total do vale:
   **/
  VALOR_TOTAL_DO_VALE = 'VALOR_TOTAL_DO_VALE',
  /**
   * Vendedor: NACIONALIDADE, NOME, ESTADO CIVIL, PROFISSÃO, DATA DE NASCIMENTO, nº RG, nº CPF/CNPJ, ENDEREÇO ELETRÔNICO, DOMICÍLIO COMPLETO COM CEP
   **/
  VENDEDOR_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP = 'VENDEDOR_NACIONALIDADE_NOME_ESTADO_CIVIL_PROFISSÃO_DATA_DE_NASCIMENTO_Nº_RG_Nº_CPF_CNPJ_ENDEREÇO_ELETRÔNICO_DOMICÍLIO_COMPLETO_COM_CEP',
  /**
   * Vendedora: Razão Social, Endereço, nº CNPJ
   **/
  VENDEDORA_RAZÃO_SOCIAL_ENDEREÇO_Nº_CNPJ = 'VENDEDORA_RAZÃO_SOCIAL_ENDEREÇO_Nº_CNPJ',
}