export enum EEventMessage {
  POS_RESULT = 'POS_RESULT',
  LAST_DAY_SALES = 'LAST_DAY_SALES',
  LAST_MONTH_SALES = 'LAST_MONTH_SALES',
  CANCELED_SALE = 'CANCELED_SALE',
  BLEED_ALERT = 'BLEED_ALERT',
  CLOSE_POS = 'CLOSE_POS',
  MINIMUM_STOCK_ALERT = 'MINIMUM_STOCK_ALERT',
  ACCUMULATED_MONTH = 'ACCUMULATED_MONTH',
  SALES_BY_DAY = 'SALES_BY_DAY',
}
