export enum EGlobalSettingsType {
    CHATCLAUDE_CONFIG = 'CHATCLAUDE_CONFIG',
    EMAIL_DEFAULT = 'EMAIL_DEFAULT',
    INVOICE_CONFIG = 'INVOICE_CONFIG',
    CHATGPT_CONFIG = 'CHATGPT_CONFIG',
    MELI_CONFIG = 'MELI_CONFIG',
    GOOGLE_AUTH = 'GOOGLE_AUTH',
    CHATGEMINI_CONFIG = 'CHATGEMINI_CONFIG',
}
