export enum EOs {
  ANDROID = 'ANDROID',
  IOS = 'IOS',
  WINDOWS_PHONE = 'WINDOWS_PHONE',
  WINDOWS = 'WINDOWS',
  LINUX = 'LINUX',
  ELECTRON = 'ELECTRON',
  OTHER = 'OTHER',
  UNKNOWN = 'UNKNOWN',
}
