export enum EPaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELED = 'CANCELED',
  PAID = 'PAID',
  REFUNDED = 'REFUNDED',
  AUTHORIZED = 'AUTHORIZED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
  DISPUTED = 'DISPUTED',
}
